### ISSUE TITLE
Simulate and document steps to configure SAML with D8P.  We have the following docs:

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-devportal-kickstart-drupal#234]
https://www.chapterthree.com/blog/how-to-configure-simplesamlphp-for-drupal-8-on-acquia

https://www.chapterthree.com/blog/adfs-and-simplesamlphp-drupal

https://www.chapterthree.com/blog/pingone-and-simplesamlphp-drupal

But the ask here is for steps that apply to customers on
1. Pantheon
2. On-prem

**Comment by kscheirer** [comment]
Also these docs
- pantheon
  - https://community.apigee.com/articles/29201/sso-integration-with-developer-portal.html 
- on-prem
  - https://community.apigee.com/articles/60901/sso-integration-via-saml-with-developer-portal-for.html

**Comment by kscheirer** [comment]
https://docs.google.com/document/d/1iuTHUTU5rzl7VAk2hnMrBzSdAF2EUcd-32H_X9ECVmA/edit#

Ready for review

**Comment by jbennett13** [comment]
Docs have been published at https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/integrate-simplesamlphp-authentication

**Comment by samhaldia** [comment]
On executing the command composer require drupal/simplesamlphp_auth:3.x-dev drupal/simplesamlphp_custom_attributes --prefer-dist
Using version ^1.1 for drupal/simplesamlphp_custom_attributes
It gives below output and deletes the core folder

./composer.json has been updated
Removing package drupal/better_exposed_filters so that it can be re-installed and re-patched.
  - Removing drupal/better_exposed_filters (3.0.0-alpha6)
Deleting web/modules/contrib/better_exposed_filters - deleted
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (8.8.5

**Comment by cnovak** [comment]
I opened a bug for you on this @samhaldia , see #355
