### ISSUE TITLE
Responsive Image styles do not use Kickstart breakpoints

### ISSUE THREAD

**Issue by cnovak** [apigee/apigee-devportal-kickstart-drupal#317]
# Description
I was looking at the responsive image styles and the images are set up to use responsive image breakpoints instead of Kickstart breakpoints. Is this configuration correct?

<img width="636" alt="responsive-image-config" src="https://user-images.githubusercontent.com/613093/73988067-6f9df900-48f6-11ea-8866-53caf0edef50.png">

**Comment by jacine** [comment]
Hey @cnovak! 👋

This was an intentional choice. We don’t need the theme breakpoints, but I left them in case anyone extending might want to use them from a sub theme (potentially with `picture`), but we’re using the `srcset` method, which is defined by the core module (like in your screenshot).  We could define 1x and 2x in the theme (that’s all that would end up there given we are using srcset), but it’s unnecessary, since the RI module gives us what we need.

During development, I analyzed all the design’s images, and created image styles (organized by aspect ratio) optimized for popular device sizes. If you look deeper into the settings you can see they don’t match up with the theme breakpoints and using the `picture` method doesn’t really make sense because we’re just changing the size, as opposed to doing art direction.  I can share my notes from when I was analyzing this if you are interested.

HTH,
Jacine 🙂

**Comment by jacine** [comment]
Notes, just in case: https://gist.github.com/jacine/cb11830d71f93f3c4d178eddc2cf4ab8

**Comment by cnovak** [comment]
Thanks @jacine for detailed answer, I was expecting this was done on purpose, glad I made sure and got a good explanation in case others look into this.
