### ISSUE TITLE
"Unable to install Apigee Kickstart Monetization due to unmet dependencies: field.field.commerce_product.add_credit.stores (field.storage.commerce_product.stores), field.field.commerce_product.add_credit.variations (field.storage.commerce_product.variations)" error

### ISSUE THREAD

**Issue by nextagencyio** [apigee/apigee-devportal-kickstart-drupal#319]
I have the D8 distro installed with Apigee Edge configured. When I try to enable the "Apigee Kickstart Monetization" experimental feature I get the following warning:

"Unable to install Apigee Kickstart Monetization due to unmet dependencies: field.field.commerce_product.add_credit.stores (field.storage.commerce_product.stores), field.field.commerce_product.add_credit.variations (field.storage.commerce_product.variations)" error

My guess is that this configuration is supposed to be provided by other modules in the project such as "Apigee Monetization Add Credit" which is enabled.

**Comment by arlina-espinoza** [comment]
Found the issue is changes in the internal entity schema of commerce entities from commerce 8.x-2.16 I'm working on updating Kickstart installer to avoid installing configuration yaml objects for this submodule, and instead re-create the configuration with code, which should make it more robust against commerce updates.

**Comment by arlina-espinoza** [comment]
@drupalninja Please review this PR: #323
