### ISSUE TITLE
Question for OnPrem Solution

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#326]
Hi Team,

A quick question came up during our discussion with the security and governance. Do we have a centralized repository which Drupal can suggest to get the dependent packages. We are not allowed to open firewall for multiple ip's/websites. Can we have a centralized Drupal approved repository location for atleast the kick starter which will have the Drupal Core and Apigee integration packages.

Thanks.,
PRadeep

**Comment by pradeepgorle13** [comment]
Had some discussion with my team and they say "We are looking out for a installer which is bundled; included in a download that comes with the kickstarter package.  Some tar/zip has all this packages bundled together and then an installation script decompresses that and the installer uses the local packages".
This would be similar to the package that APIGEE has provided within the product (Which was based on Drupal 7)

**Comment by cnovak** [comment]
This seems to be a duplicate of #321 ? 

We are not planning to create a packaged bundle of all dependencies since we would just be pulling from packagist.org and packages.drupal.org, and this would add a delay on getting latest versions and security updates.

You do need at least one environment you can pull down dependencies, do any validation against, and then check into a source control system so that you can put changes on production and any other environments you have.

I would believe this would be the same process you would use for keeping the server OS and dependencies up to date - you need to be able to run updates for the Linux OS package manager of your choosing to keep the operating system and dependencies up to date.

The only other option I can think of is to use https://packagist.com to have your own private repository so that packages can be reviewed and restricted.

I will close this issue, but add any comments if you have any more questions.
