### ISSUE TITLE
Devportal Customization Question

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#342]
Hi Guys, 

Want to understand 
1. Where I can get the best resources/documentation for the APIGEE Devportal customization and flows. (ex: I wanted to have a user flow for both the App Developer, App consumer etc.,)
2. When i do the changes, how can i capture those changes in the GIT?

To add:
I am already going through 
https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/customize-your-developer-portal

Thanks.,

**Comment by cnovak** [comment]
# Customization and flows
Can you explain your use case(s) more? I am not sure what you mean by "customization and flows", or "user flow for both the App Developer, App consumer etc.". What are you trying to do?

# Capturing changes
Configuration changes are now stored using a system called "configuration management".  The configuration can be exported and stored in source control. Check out the [Drupal 8 documentation on configuration management](https://www.drupal.org/docs/8/configuration-management) for more info.

**Comment by pradeepgorle13** [comment]
@cnovak Thanks for the immediate reply. What I mean by the customization and Flows is 
 > For Customization of the themes(Changing from the default Logo, taking our own fonts etc..,)
 > For Flows - How to create different flows 
        Eg:
           For the App Developer or internal user- He logs in, He will upload his OAS document, tag the 
           product within the organization, tag its App Owner and submits the request for approval to 
           expose API.
          For the App Consumer or external user- He Registers, then he will select an API and requests 
          for the API key/ credentials, then submits the request for the approval)

Please let me know, if you need any other information.

Thanks.

**Comment by cnovak** [comment]
You are welcome! Check out our [Kickstart documentation](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart) on how to theme the site, change logo, etc.

For the API developer flow, you will need to do your own customizations using either an external system making calls to the Drupal portal through REST APIs, or build out a custom solution using a custom module or some contributed modules such as the [Workflow module](https://www.drupal.org/docs/8/core/modules/workflows/overview). We are planning on [changing API Doc entities into Drupal Nodes](https://github.com/apigee/apigee-api-catalog-drupal/issues/71) instead of using a custom entity, which could help you to use the Workflow module, so follow that issue to check it out when we have in the change. Check out our [API Catalog documentation](https://www.drupal.org/docs/8/modules/apigee-api-catalog) for info on connecting through REST APIs.  

For the App consumer, that flow already exists using [API Product approvals](https://docs.apigee.com/api-platform/publish/what-api-product),  except for the fact you probably want to notify the approvers when a new app is created. Check out https://github.com/apigee/apigee-edge-drupal/issues/267 for the rules integration which will allow you to email admins when an app is created.

**Comment by pradeepgorle13** [comment]
> You are welcome! Check out our [Kickstart documentation](https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart) on how to theme the site, change logo, etc.
> 
> For the API developer flow, you will need to do your own customizations using either an external system making calls to the Drupal portal through REST APIs, or build out a custom solution using a custom module or some contributed modules such as the [Workflow module](https://www.drupal.org/docs/8/core/modules/workflows/overview). We are planning on [changing API Doc entities into Drupal Nodes](https://github.com/apigee/apigee-api-catalog-drupal/issues/71) instead of using a custom entity, which could help you to use the Workflow module, so follow that issue to check it out when we have in the change. Check out our [API Catalog documentation](https://www.drupal.org/docs/8/modules/apigee-api-catalog) for info on connecting through REST APIs.
> 
> For the App consumer, that flow already exists using [API Product approvals](https://docs.apigee.com/api-platform/publish/what-api-product), except for the fact you probably want to notify the approvers when a new app is created. Check out [apigee/apigee-edge-drupal#267](https://github.com/apigee/apigee-edge-drupal/issues/267) for the rules integration which will allow you to email admins when an app is created.

Thanks @cnovak for answering the question
