### ISSUE TITLE
How to upgrade the existing Apigee distribution to newer version?

### ISSUE THREAD

**Issue by mrdhanasekaran89** [apigee/apigee-devportal-kickstart-drupal#351]
Hi Team,

In one of my project, I am using 8.7.10 version of Apigee kickstart distribution. Now I want to upgrade it to latest version to avail the latest updates and fixes.

Can you please provide the detailed steps to upgrade to latest version of Apigee kickstart?

Thanks
M.Dhanasekaran

**Comment by shadcn** [comment]
Hey @mrdhanasekaran89, this should be easy if you're using the [Composer project](https://github.com/apigee/devportal-kickstart-project-composer).

## Note
First, make sure you have not made any changes to the `apigee_devportal_kickstart` profile. If you did, you will need to capture the changes manually and re-apply them later.

Otherwise all changes will be lost.

## Updating
1. Make sure you're running the latest version of composer: 

```
composer self-update
```

2. Go to the root of your site: 

```
cd /path/to/kickstart
```

3. Run the following command to update all packages

```
composer update --with-dependencies --optimize-autoloader
```

4. Next. run any database updates: 

```
drush updb
```

5. Clear the Drupal cache: 

```
drush cr
```

Hope this helps.

**Comment by cnovak** [comment]
Added this info to docs: https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/get-started-with-kickstart#s-upgrading-kickstart

**Comment by cnovak** [comment]
Reopening - @arshad shouldn't the step 3. above be `composer update --with-dependencies`, along with optional flag ` --optimize-autoloader` to speed up performance?

**Comment by shadcn** [comment]
@cnovak Yes you're right. I've updated the comment above. Thank you.

Should we also add an `UPDATE.md` to https://github.com/apigee/devportal-kickstart-project-composer?

**Comment by cnovak** [comment]
@arshad put in info to README to point to our documentation on how to update and install now.
