### ISSUE TITLE
Drupal SMTP issue

### ISSUE THREAD

**Issue by vinayporeddy** [apigee/apigee-devportal-kickstart-drupal#385]
## Description
SMTP module is not able to send emails.

## Steps to Reproduce

Setup smtp module/configure and try sending emails

## Actual Behavior
We are seeing below error while sending emails.
Error sending e-mail from xxx@xxx.com to xxx@xxx.com: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting                                     
 Error sending email (from xxx@xxx.com to xxx@xxx.com with reply-to not set). | Error sending email (from xxx@xxx.com to xxx@xxx.com with reply-to not set).

Below suggestion didn't help.
https://www.drupal.org/project/smtp/issues/2622678

## Expected Behavior
Should send emails

## Screenshots
NA

## Notes
It works directly  on linux box to isolate issue with firewall/any smtp issues.

## Version Info
Drupal Version
8.8.5
PHP
Version
7.3.11 
SMTP: PHPMAILER LIBRARY
6.1.6

**Comment by arunz6161** [comment]
@vinayporeddy this issue is unrelated to the kickstart module or any Apigee Drupal 8 module. You may want to set the right logging level in SMTP module to narrow down further on the error message.

**Comment by cnovak** [comment]
@vinayporeddy check out the [SMTP project page](https://www.drupal.org/project/smtp) for a link to the issue queue,  you can add a new issue or search to see if someone has had the same issue. I usually find this to be an issue w/the STMP server configuration, use the debugging in the module to figure out what the problem is.  Sometimes SMTP servers will disallow connections to servers incorrectly configured with replyto or coming from the wrong domain.

**Comment by vinayporeddy** [comment]
@arunz6161 ..Apigee support routed to log a request and hence got to create it here.
@cnovak  Did run tcpdump and we have observed issue with connections and adjust the SMTP configuration which resolved the issue.
