### ISSUE TITLE
Multiple Servers Support in the APIGEE Drupal Developer Portal

### ISSUE THREAD

**Issue by pradeepgorle13** [apigee/apigee-devportal-kickstart-drupal#484]
Guys,

We are looking for a feature similar to what we see in the Swagger editor for multiple Endpoints in the Open API Spec.
Please find the Servers sample below
![image](https://user-images.githubusercontent.com/56166711/119533945-5ff92c80-bd54-11eb-877e-7bce85b322fe.png)

When it comes Swagger editor
![image](https://user-images.githubusercontent.com/56166711/119533878-4c4dc600-bd54-11eb-9849-d39fbdcc3b72.png)

When it comes to Drupal Developer Portal
![image](https://user-images.githubusercontent.com/56166711/119533758-2fb18e00-bd54-11eb-942b-9b5ee2eb9c98.png)

We need to get the same pattern that we are seeing in the Swagger Editor. Do we have any option in Apigee Kickstarter to show the multiple Servers (instead of only one).

**Comment by giteshk** [comment]
Hi @pradeepgorle13 

This is not supported currently by the SmartDocs renderer library.  
If you are trying to display the list of hostnames to let consumers know what environment to use. You can add that information in the description field.

We have documented how to enable additional renderers including Swagger UI  in our [docs](https://www.drupal.org/docs/8/modules/apigee-api-catalog/customize-your-api-catalog#s-displayopenapi-specs-using-other-rendering-formats).

**Comment by earth2marsh** [comment]
Note that one of the most common mistakes in writing OpenAPI documents is to use `servers` to describe different software development lifecycle stages within the same document. This is because there will be times where the contract described by the OpenAPI document will be different. In that case, I'd recommend using different revisions of the same document with the server set to match, as they are effectively different contracts.

A counter example is when you have the same interface available on different servers, such as sandbox vs a production endpoint. That is a story we're considering adding to the SmartDocs roadmap, but it isn't available today.

**Comment by pradeepgorle13** [comment]
@giteshk  , Thanks for the Solution. Hope this will fix our requirement.
@earth2marsh , Thanks for the Info, We are following the standard process you suggested.

**Comment by pradeepgorle13** [comment]
Thanks guys
