### ISSUE TITLE
By when we can expect the stable release of Apigee Devportal with Drupal 8 ?

### ISSUE THREAD

**Issue by mohit-wadhwa** [apigee/apigee-devportal-kickstart-drupal#99]

**Comment by cnovak** [comment]
We plan to have a 1.0 release as soon as we finalize our last features and review for any critical issues.  We consider this will happen in weeks, not months.  We recently promoted this project to beta since we consider functionality complete and no major issues in functionality.

Let us know if you run into any critical issues in this issue queue so that we can properly evaluate our release schedule.
